name: Runs on Jupyter4NFDI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  notebooks:
    runs-on: ubuntu-latest
    environment: jupyter4nfdi
    steps:
      - name: Run notebooks via papermill on Jupyter4NFDI
        uses: NFDI-Jupyter/ghactions/.github/actions/notebooks@main
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          api_url: "https://jupyter-jsc-dev1.fz-juelich.de/hub/api/job"
          # notebook_dirs: '["notebooks", "examples"]' # Only check specific folders in your repo
          token: ${{ secrets.JUPYTERHUB_API_TOKEN }}
